services:
  web:
    build: .
    volumes:
      - .:/code
  web_migrate:
    extends:
      service: web
    command: python /code/educa/manage.py migrate
  web_run:
    extends:
      service: web
    command: python /code/educa/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - web_migrate
    environment:
      PYTHONPATH: "/code/educa"
      DJANGO_SETTINGS_MODULE: "educa.settings"
  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data
